newborn/config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'

  resources :users
  get 'welcome/index'
  root 'welcome#index'
end

newborn/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

newborn/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates_length_of :password, :minimum => 6, :on => :create
end

newborn/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :require_login

private

  def require_login
    unless current_user
      redirect_to login_url
    end
  end
end

newborn/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login

  def new
  end

  def create
    session = params[:session]
    user = User.find(session[:name])

    if user && user.authenticate(session[:password])
      log_in user
      redirect_to root_url
    else
      flash[:danger] = 'Invalid email/password combination'
      render "new"
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

newborn/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, :except => [:index, :show]

  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      flash[:danger] = "Form is invalid"
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

newborn/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @current_user = current_user
  end
end

newborn/app/helpers/application_helper.rb
module ApplicationHelper
end

newborn/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.name
  end

  def current_user
    @current_user ||= User.find_by(name: session[:user_id])
  end

  def log_out
    session[:user_id] = nil
  end
end

newborn/app/helpers/users_helper.rb
module UsersHelper
end

newborn/app/helpers/welcome_helper.rb
module WelcomeHelper
end

newborn/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newborn</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

newborn/app/views/users/index.html.erb
<h1>Listing users</h1>
 
<table>
  <tr>
    <th>Name</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to 'New User', new_user_path %>
</p>

newborn/app/views/users/new.html.erb
<h1>New user</h1>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<% if @user.errors.any? %>
  <ul>
  <% for message_error in @user.errors.full_messages %>
    <li><%= message_error %></li>
  <% end %>
  </ul>
<% end %>

<%= form_with scope: :user, url: users_path, local: true do |form| %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :password %>
    <%= form.password_field :password%>
  </p>
  <p>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation%>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

newborn/app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <%= link_to 'List Users', users_path %>
</p>

newborn/app/views/welcome/index.html.erb
<h1>Welcome <%= current_user.name %></h1>

<p><%= link_to "Log out", logout_path, method: :delete %></p>